### ISSUE TITLE
Telemetry

### ISSUE THREAD

**Issue by ghostzero** [own3d/own3dpro-obs-plugin#13]
## Motivation

We would like to know how many active users we have. Currently, we can only roughly determine these statistics by knowing how many users interact with the Overlay & Alerts Store.

## Task

We want to send a ping to our API every time OBS Studio is started. There will be the endpoint `POST https://own3d.pro/api/v1/obs/ping`. In the body of the endpoint the license key will be transmitted.

Please consider the privacy. Before we do the ping, we will educate the user about our Privacy Policy. If the user does not agree, then a flag should be transmitted late at the theme store (e.g. Do-Not-Track header at all our browser sources (if possible)). 

## Acceptance criteria

* The user gets a one-time message at startup asking for consent for telemetry (including information about privacy policy).
* If the user has agreed, then a ping is sent at OBS startup. (if necessary handle the ping exactly the same way as generating the machine token, see: https://github.com/own3d/own3dpro-obs-plugin/issues/10#issuecomment-769813134).
* A Do-Not-Track header is sent to all of our browser sources, if the user did not agree.

**Comment by Xaymar** [comment]
> A Do-Not-Track header is sent to all of our browser sources, if the user did not agree.

Not possible to set, no API functionality is available for it. Since it is required to agree to the privacy policy anyway, it may be safe to just assume Do-Not-Track is off.

**Comment by Xaymar** [comment]
Phase 1: Active Plugin ping
Phase 2: Which features are being used ping
Phase 3: Frontend events, Scene Collection, Design tracking.
