### ISSUE TITLE
Docks

### ISSUE THREAD

**Issue by ghostzero** [own3d/own3dpro-obs-plugin#14]
## Motivation

We want to offer certain elements in the OWN3D Pro dashboard as a dock in OBS Studio. Examples: Eventlist or Quick Switch from saved Alert Themes.

## Task

The creation of Docks. The docks should be simple web sources in the first step. The exact link is still TBD.

## Acceptance Criteria

- As a user I can add my eventlist as a dock into OBS via View > Docks > Eventlist.

**Comment by Xaymar** [comment]
- [x] Event List #19
