### ISSUE TITLE
Auto Check for Updates

### ISSUE THREAD

**Issue by ghostzero** [own3d/own3dpro-obs-plugin#15]
## Motivation

Currently, users are only notified of updates when they open the store. The entire store is then also blocked.

## Task

Similar check of updates system as StreamFX. Already discussed with Michael.

## Acceptance criteria

* The plugin checks (e.g. at startup) if a new update is available and informs the user about it. The version information comes from GitHub.

Note: Show changelog? When the plugin has been updated, or before it has been updated?

**Comment by ghostzero** [comment]
Just for the protocol: The url to check own3d pro releases is available at:
`https://own3d.pro/api/v1/obs/releases`

It's a cached version of the github release api endpoint. The cache is valid for 2 hours.

**Comment by Xaymar** [comment]
Opting against the "Testing" channel integration, as it is pointless for a plugin that only has a release once in a while. It's also pointless because users can't read.
