### ISSUE TITLE
Can't find OWN3D Pro in Tools menu

### ISSUE THREAD

**Issue by ghostzero** [own3d/own3dpro-obs-plugin#3]
## Observed behavior

We currently have a few users who report that they are not seeing OWN3D Pro in the Tools menu. Apparently the plugin is not loaded because it was not found.

Through remote sessions we might find out that the OWN3D Pro plugin is located in the folder `C:\Program Files (x86)\...` instead of `C:\Program Files\...` was installed.

![unknown](https://user-images.githubusercontent.com/6547306/99794940-44a23000-2b2b-11eb-974f-62372d625d12.png)

Futuremore, during the installation of the plugin the program does not ask for an installation path. 

## Expected results

The OBS Plugin is installed in the correct folder and loaded by OBS.

## Current Workaround

https://github.com/own3d/own3dpro-obs-plugin/wiki/Installation#i-cant-find-own3d-pro-in-tools-menu

**Comment by Xaymar** [comment]
Bug may be related to querying HKLM32 instead of HKLM

**Comment by Xaymar** [comment]
See PR #9

**Comment by ghostzero** [comment]
Thanks. Got positive feedback. Great work!

**Comment by bruhwhatsmyname** [comment]
bruh it still not working for me tho

**Comment by ghostzero** [comment]
@bruhwhatsmyname can you please provide more information instead of just blaming? This would be more productive, otherwise we will ignore your message.

You may provide us with following information:

```
### System Information
<!-- Either fill out the following or put latest log file url (In OBS select Help > Log Files > Upload last Log File). -->
- Software Version: [e. g. 1.0.0, 1.2.1, ... - NEVER LATEST]
- Operating System: [e. g. Windows, Debian, Ubuntu, RedHat, FreeBSD, ...]
- Kernel Version: [e. g. 1903/1809 (Windows), 4.12 (Linux), ...]
- CPU: [e. g. Intel i7, AMD Zen2, Qualcomm, ...]
- GPU: [e. g. Nvidia RTX 2xxx Series, AMD Radeone 5xxx Series, ...]
- RAM: [e. g. 16GB, 32GB, 64GB, ...]
```

**Comment by mishtidahi** [comment]
Can't find OWN3D Pro in Tools menu
[last log file](https://obsproject.com/logs/n9omw-OoC2PKGTji)

**Comment by Xaymar** [comment]
> Can't find OWN3D Pro in Tools menu
> [last log file](https://obsproject.com/logs/n9omw-OoC2PKGTji)

1. Do you happen to have a Firewall (Windows Firewall, Norton Antivirus, etc.) active?
2. Are you in a VPN or Proxy based network?
3. Can you access [own3d.pro](https://own3d.pro) just fine?

**Comment by mamasmiley21** [comment]
I was also struggling with getting to see it. it ended up being the same ol' solution to just about every tech problem and it was log out and then back in again and poof like magic there it was. I don't know if that will help anyone else having issues. but it's worth a try.  also please ignore the bad typing and grammar of this post. :/

**Comment by rhino231** [comment]
It's not showing up in my menu either, here is my log file. 
[2023-03-30 02-00-14.txt](https://github.com/own3d/own3dpro-obs-plugin/files/11108360/2023-03-30.02-00-14.txt)

**Comment by TheSlayerOfCPUs** [comment]
@mamasmiley21 What did you sign out on OBS or OWN3dPro?

**Comment by rhino231** [comment]
I figured it out, but there's some miscommunication on the website saying
that owned pro is in the tools menu when in fact it has it's own menu next
to the tools menu.

**Comment by litterKat** [comment]
Ok so i figured it out lol, I was having the same issue and the best way to resolve it is to:
1. uninstall both Obs Studio and OWN3D,
2. before opening obs, set the settings in obs as admin (right click on the icon in properties and then compatibility.
3. When you get into OBS, OWN3D still isn't under tools, but by opening the store through the OWN3D label, I was able to login through there !
4. You can add chat and alerts through the sources button and it should pop up
Hope this helps anyone! ^^
