### ISSUE TITLE
Chat does not support Cyrillic!

### ISSUE THREAD

**Issue by kiskaserver** [own3d/own3dpro-obs-plugin#33]
### Description
The plugin for chat OWN3D does not work correctly. Because it has preprogrammed fonts and therefore does not output Cyrillic. My ticket with screenshots attached.
https://own3dprosupport.zendesk.com/hc/en-us/requests/24812
After analyzing your plugin I found the following lines of code:
```
std::string_view fonts[] = {
    "Alfa Slab One", "Anton", "Arbutus", "Audiowide", "Azonix", "Bangers", "Bebas Neue",
    "Black Ops One, Brick Sans, Built Titling, Bungee, Chewy, Cinzel, Evogria,
    "Fredoka One," "Gotham Ultra," "Lobster," "Luckiest Guy," "Nemesis Grant," "Open Sans," "Oswald,
    "Pacifico," "Patua One," "Permanent Marker," "Pirata One," "Press Start 2P," "Qualy," "Righteous,
    "Roboto, Sancreek, Shojumaru, Sigmar One, Slackey, Squada One, Teko,
    "Ubuntu," "UnifrakturCook," "Vampiro One," "Wallpoet."
};
```
Which tells you that the fonts are pre-programmed, not parsed online from the Windows system. I paid for a subscription and want an adequate software solution that supports UKRAINIAN SYMBOLS AND LETTERS.
![test2](https://user-images.githubusercontent.com/32369874/164565592-12a41f1e-76c3-4ea6-99d8-6ef66d56a6ba.png)
![copy](https://user-images.githubusercontent.com/32369874/164565619-11efe0c0-f2c3-43d8-877a-272a351b7589.png)
In the screenshots clearly shows that when I write English letters and symbols chat reproduces them, but when I try to write Cyrillic letters and symbols chat just does not display them. 
At the same time as the fonts supporting Cyrillic are installed in my OS.

### System Information
- Software Version: 27.2.4 (64-bit, windows)
- Operating System: Windows 10
- Kernel Version: Windows Version: 10.0 Build 19044 (release: 2009; revision: 1645; 64-bit)
- CPU: AMD Ryzen 5 3600
- GPU: Nvidia RTX 2060
- RAM: 16GB
(https://obsproject.com/logs/ETGVDYgoXlLidPFS)

**Comment by Xaymar** [comment]
Most likely a problem with a lack of fallback fonts in CSS on the underlying widget.

**Comment by kiskaserver** [comment]
Hm? Thi is a I do not think, if you use a browser or text GDI + which displays all the fonts are ok, but it is in the plugin own3d chat is a restriction on fonts, that is, you can only use those provided by the developer of the plugin.

**Comment by Xaymar** [comment]
> Hm? Thi is a I do not think, if you use a browser or text GDI + which displays all the fonts are ok, but it is in the plugin own3d chat is a restriction on fonts, that is, you can only use those provided by the developer of the plugin.

The underlying implementation is done via Browser Source, so the problem is with the Own3d chat widget itself not providing a fallback font for characters not supported in the given font.
