### ISSUE TITLE
The download of a Theme stuck by 66%

### ISSUE THREAD

**Issue by ghostzero** [own3d/own3dpro-obs-plugin#4]
## Observed behavior

Some users report that their download hangs at 66%. Users also cannot estimate that this process may take some time.

Apparently this error occurs when you have a special character in your username under %appdata%.

The following log has been sent to us:

[vUnYNHIuV7ubZRLE.txt](https://github.com/own3d/own3dpro-obs-plugin/files/5573207/vUnYNHIuV7ubZRLE.txt)

## Expected results

The installation is completed successfully, in case of an error an error message is displayed to inform the user.

## Current Workaround

Currently there is no workaround available.

**Comment by Xaymar** [comment]
PRs: #7 #6

**Comment by ghostzero** [comment]
Thanks! Version is in testing 👍

**Comment by ghostzero** [comment]
Update: Unfortunately, we still getting the ` [Own3d.TV] Installation of Theme 'Avoid' failed due to error: Failed to install theme, data.json may be corrupted.` error.

https://obsproject.com/logs/Xksv1bkw9AaG4I9a

[data.txt](https://github.com/own3d/own3dpro-obs-plugin/files/5607124/data.txt)

**Comment by Xaymar** [comment]
Further PRs: #8

**Comment by ghostzero** [comment]
We will close this now, because we released some fixes and waiting for further feedback.
