### ISSUE TITLE
Support for Mac

### ISSUE THREAD

**Issue by ghostzero** [own3d/own3dpro-obs-plugin#5]
We are considering introducing support for Mac.

Current User Feedback: 
https://feedback.own3d.pro/posts/5/suuport-for-linux-and-mac

**Comment by Xaymar** [comment]
Temporarily stopped. For unknown reasons, loading the own3d.so library makes the vtable explode on MacOS in spectacular ways.

**Comment by Xaymar** [comment]
For future unpausing:
- Both Linux and MacOS libraries export more symbols than they need to, so most likely the default visibility needs to be changed to fix it.
    - Sadly this doesn't seem to affect standard C++, which always exports no matter what - but that doesn't seem to be a problem.
- QCefWidget seems to be the primary cause of this, which is also exported by obs-browser.so as well as own3d.so. 
- Might also have collisions from libzip and zlib, but I haven't found any.
- Not related to static or shared libraries so far.

**Comment by Mparker25** [comment]
Over a year later? Any support for mac?
